// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: git-contributions-draw/v1/git-contributions-draw.proto

package git_contributions_draw

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GitContributionsDraw_GetDraw_FullMethodName = "/git_contributions_draw.v1.GitContributionsDraw/GetDraw"
)

// GitContributionsDrawClient is the client API for GitContributionsDraw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitContributionsDrawClient interface {
	GetDraw(ctx context.Context, in *GetDrawRequest, opts ...grpc.CallOption) (*GetDrawResponse, error)
}

type gitContributionsDrawClient struct {
	cc grpc.ClientConnInterface
}

func NewGitContributionsDrawClient(cc grpc.ClientConnInterface) GitContributionsDrawClient {
	return &gitContributionsDrawClient{cc}
}

func (c *gitContributionsDrawClient) GetDraw(ctx context.Context, in *GetDrawRequest, opts ...grpc.CallOption) (*GetDrawResponse, error) {
	out := new(GetDrawResponse)
	err := c.cc.Invoke(ctx, GitContributionsDraw_GetDraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitContributionsDrawServer is the server API for GitContributionsDraw service.
// All implementations must embed UnimplementedGitContributionsDrawServer
// for forward compatibility
type GitContributionsDrawServer interface {
	GetDraw(context.Context, *GetDrawRequest) (*GetDrawResponse, error)
	mustEmbedUnimplementedGitContributionsDrawServer()
}

// UnimplementedGitContributionsDrawServer must be embedded to have forward compatible implementations.
type UnimplementedGitContributionsDrawServer struct {
}

func (UnimplementedGitContributionsDrawServer) GetDraw(context.Context, *GetDrawRequest) (*GetDrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDraw not implemented")
}
func (UnimplementedGitContributionsDrawServer) mustEmbedUnimplementedGitContributionsDrawServer() {}

// UnsafeGitContributionsDrawServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitContributionsDrawServer will
// result in compilation errors.
type UnsafeGitContributionsDrawServer interface {
	mustEmbedUnimplementedGitContributionsDrawServer()
}

func RegisterGitContributionsDrawServer(s grpc.ServiceRegistrar, srv GitContributionsDrawServer) {
	s.RegisterService(&GitContributionsDraw_ServiceDesc, srv)
}

func _GitContributionsDraw_GetDraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitContributionsDrawServer).GetDraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitContributionsDraw_GetDraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitContributionsDrawServer).GetDraw(ctx, req.(*GetDrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitContributionsDraw_ServiceDesc is the grpc.ServiceDesc for GitContributionsDraw service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitContributionsDraw_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "git_contributions_draw.v1.GitContributionsDraw",
	HandlerType: (*GitContributionsDrawServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDraw",
			Handler:    _GitContributionsDraw_GetDraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git-contributions-draw/v1/git-contributions-draw.proto",
}
