// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: 1.0.0
// Version Date:

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"github.com/chaos-io/gokit/tracing"
	"github.com/go-kit/kit/log"
	grpctransport "github.com/go-kit/kit/transport/grpc"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc/metadata"

	// this service api
	pb "github.com/liankui/git-contributions-draw/go/git-contributions-draw/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC GitContributionsDrawServer.
func MakeGRPCServer(endpoints Endpoints, tracer trace.Tracer, logger log.Logger) pb.GitContributionsDrawServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
		grpctransport.ServerErrorLogger(logger),
	}

	addTracerOption := func(methodName string) []grpctransport.ServerOption {
		if tracer != nil {
			return append(serverOptions, grpctransport.ServerBefore(tracing.GRPCToContext(tracer, methodName)))
		}
		return serverOptions
	}

	return &grpcServer{
		// GitContributionsDraw
		getDraw: grpctransport.NewServer(
			endpoints.GetDrawEndpoint,
			DecodeGRPCGetDrawRequest,
			EncodeGRPCGetDrawResponse,
			addTracerOption("GetDraw")...,
		),
	}
}

// grpcServer implements the GitContributionsDrawServer interface
type grpcServer struct {
	pb.UnimplementedGitContributionsDrawServer

	getDraw grpctransport.Handler
}

// Methods for grpcServer to implement GitContributionsDrawServer interface

func (s *grpcServer) GetDraw(ctx context.Context, req *pb.GetDrawRequest) (*pb.GetDrawResponse, error) {
	_, rep, err := s.getDraw.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetDrawResponse), nil
}

// Server Decode

// DecodeGRPCGetDrawRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetDraw request to a user-domain GetDraw request. Primarily useful in a server.
func DecodeGRPCGetDrawRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetDrawRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCGetDrawResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetDraw response to a gRPC GetDraw reply. Primarily useful in a server.
func EncodeGRPCGetDrawResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetDrawResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
